title: allan bunch
logo: ./assets/images/profile-photo-neutral@275x275.png
description: Visionary | Innovator | Futurist
theme: jekyll-theme-minimal

author:
  name: Allan

# Navigation links
nav_links:
  - name: Home
    url: /
  - name: Projects
    url: /projects/
  - name: Contact
    url: /contact/

# Optional social links
github_username: allanbunch
linkedin_username: allanbunch
