title: allan bunch
logo: ./assets/images/profile-photo-neutral@275x275.png
description: Visionary | Innovator | Futurist
theme: jekyll-theme-minimal

author:
  name: Allan

# Social links
github_username: allanbunch
linkedin_username: allanbunch

# Custom build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap