title: allan bunch
logo: https://github.com/allanbunch/allanbunch.github.io/assets/4503640/a73896aa-15d0-4d92-adc7-f8b1236d3824
description: Visionary | Innovator | Futurist
theme: jekyll-theme-minimal
